# Generated by Django 4.2.2 on 2023-06-21 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='conv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=20, max_digits=25)),
                ('longitude', models.DecimalField(decimal_places=20, max_digits=25)),
                ('name', models.CharField(max_length=30)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('where', models.TextField()),
                ('time', models.TextField()),
                ('menu', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=20, max_digits=25)),
                ('longitude', models.DecimalField(decimal_places=20, max_digits=25)),
                ('name', models.CharField(max_length=30)),
                ('stair', models.IntegerField(blank=True)),
                ('depart', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('slope', models.IntegerField(default=0)),
                ('near', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
