# Generated by Django 4.2.2 on 2023-06-24 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='stair',
            new_name='floor',
        ),
        migrations.RemoveField(
            model_name='info',
            name='slope',
        ),
    ]
