# Generated by Django 4.2.2 on 2023-06-24 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_stair_info_floor_remove_info_slope'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='floor',
            field=models.TextField(blank=True),
        ),
    ]
