# Generated by Django 4.2.2 on 2023-06-21 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_conv_remove_profile_nickname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='logintime',
        ),
    ]
