# Generated by Django 4.2.2 on 2023-06-26 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_info_floor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='depart',
            field=models.IntegerField(),
        ),
    ]
