# Generated by Django 4.2.2 on 2023-06-26 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_bookmark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='attendance',
        ),
    ]
